### ISSUE TITLE
[feature] handle redirections

### ISSUE THREAD

**Issue by ebuildy** [prantlf/nettime#15]
Thanks you for this library.

I just noticed when the server send a 302 response, the new URL is not analyzed.

Is it possible to handle redirections ?

**Comment by prantlf** [comment]
Yes, it is. Thanks for the idea! I worked around this by using the URL, which did not redirect, but it may not be always easy :-)

I added a new option `followRedirects` and command line parameter `-L, --location` modelled after the `curl` command line. When enabled, it will prefix every request with its URL:

    ❯ nettime -L http://google.com
    URL: http://google.com

    Phase             Finished Duration
    -----------------------------------
    Socket Open         0.005s   0.005s
    DNS Lookup          0.030s   0.025s
    TCP Connection      0.042s   0.012s
    First Byte          0.081s   0.039s
    Content Transfer    0.081s   0.001s
    Socket Close        0.087s   0.005s
    -----------------------------------
    Response: HTTP/1.1 301 Moved Permanently

    URL: http://www.google.com/

    Phase             Finished Duration
    -----------------------------------
    Socket Open         0.000s   0.000s
    DNS Lookup          0.001s   0.001s
    TCP Connection      0.012s   0.011s
    First Byte          0.083s   0.071s
    Content Transfer    0.111s   0.028s
    Socket Close        0.111s   0.000s
    -----------------------------------
    Response: HTTP/1.1 200 OK

Programmatically, if `followRedirects` is set to `true`, the result will be array of objects, instead of an object, to accommodate one or more request results. Also, the result objects will include a new `url` property.

I included it in the new 4.0.0, together with an update for the contemporary Node.js environment. What do you think?

**Comment by ebuildy** [comment]
it sound very good! thanks you
